title: Adam Gutonski
logo: /assets/img/logo.png
description: 👋 Hi, I'm Adam.  I'm a software engineer with a focus on data, especially geospatial data.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
resume_file: "/assets/resume/resume.pdf"
